export default {
  products: [
    {
      id: 1,
      image: "/images/maize.jpg",
      name: "Yellow maize",
      price: 150,
      currency: "Ugsh",
      quantity: 5500,
      unit: "Kg",
      subCategory: "Maize",
      category: "Cereals",
      ratings: 10,
      numReviews: 35,
      description: "Yellow maize",
    },
    {
      id: 2,
      image: "/images/beans.jpg",
      name: "Kidney Beans",
      price: 300,
      currency: "Ksh",
      quantity: 3000,
      unit: "Kg",
      subCategory: "Beans",
      category: "Cereals",
      ratings: 7,
      numReviews: 15,
      description: "Good crops Kidney Beans",
    },
    {
      id: 3,
      image: "/images/irish.jpg",
      name: "Irish Potatoes",
      price: 350,
      currency: "Rwf",
      quantity: 500,
      unit: "Kg",
      subCategory: "irishPotatoes",
      category: "Potatoes",
      ratings: 6.5,
      numReviews: 22,
      description: "Good crops Irish Potatoes",
    },
    {
      id: 4,
      image: "/images/avocado.jpg",
      name: "Avocadoes",
      price: 100,
      currency: "Rwf",
      quantity: 250,
      unit: "Piece",
      subCategory: "avocadoes",
      category: "Fruits",
      ratings: 5,
      numReviews: 20,
      description: "Good crops Avocadoes",
    },
    {
      id: 5,
      image: "/images/tomatoes.jpg",
      name: "Red tomatoes",
      price: 700,
      currency: "Rwf",
      quantity: 300,
      unit: "Kg",
      subCategory: "tomatoes",
      category: "Vegetables",
      ratings: 8,
      numReviews: 10,
      description: "Good crops Red tomatoes",
    },
    {
      id: 6,
      image: "/images/rice.jpg",
      name: "Pakistanese Rice",
      price: 8,
      currency: "$",
      quantity: 2300,
      unit: "Kg",
      subCategory: "rice",
      category: "Cereals",
      ratings: 8,
      numReviews: 10,
      description: "Good crops Pakistanese Rice",
    },
  ],

  categories: [
    {
      id: 1,
      name: "Cerials",
    },
    {
      id: 2,
      name: "Fruits",
    },
    {
      id: 3,
      name: "Vegetables",
    },
    {
      id: 4,
      name: "Potatoes",
    },
  ],
};
